#include "GPIO_Config.h"
///////////////////////////port F//////////////////////////////////////
//led in portF
void vGPIO_LED_INT(void){
	vActive_CLK_GPIO(GPIO_CLK_F);
	vGPIO_UNLOCK(GPIO_F);
	vGPIO_Commit_Change_ALL(GPIO_F);
	
	vGPIO_DIR_WRITE_PIN(GPIO_F,1,OUTPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_F,2,OUTPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_F,3,OUTPUT);
	
	vGPIO_MODE_SETTING_PIN(GPIO_F,Digital,Normal_GPIO,1);
	vGPIO_MODE_SETTING_PIN(GPIO_F,Digital,Normal_GPIO,2);
	vGPIO_MODE_SETTING_PIN(GPIO_F,Digital,Normal_GPIO,3);
	
	vGPIO_DATA_WRITE_ALL(GPIO_F,COLOR_OFF);
}


void vGPIO_LED_COLOR_OUT(uint8 color){
	vGPIO_DATA_WRITE_RESET_ALL(GPIO_F,0x0E);
	vGPIO_DATA_WRITE_SET_ALL(GPIO_F,color);
}

//GPIOF switches
void vGPIO_SWITCH_INT(void){
	vActive_CLK_GPIO(GPIO_CLK_F);
	vGPIO_UNLOCK(GPIO_F);
	vGPIO_Commit_Change_ALL(GPIO_F);
	
	vGPIO_MODE_SETTING_PIN(GPIO_F,Digital,Normal_GPIO,0);
	vGPIO_MODE_SETTING_PIN(GPIO_F,Digital,Normal_GPIO,4);
	
	vGPIO_DIR_WRITE_PIN(GPIO_F,0,INPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_F,4,INPUT);
	
	vGPIO_INPUT_MODE_PIN(GPIO_F,PULL_UP_R,0);
	vGPIO_INPUT_MODE_PIN(GPIO_F,PULL_UP_R,4);
	
	
}

uint8 u8GPIO_SWITCH_Input(uint8 sw){
	uint8 val;
	if((sw==0)||(sw==4)){
		if(u8GPIO_DATA_READ_PIN(GPIO_F,sw)==0)val=1;
		else val=0;
	}
	else val=0;
	return val;
	
}
/////////////////////LCD ---->GPIO B(0-->7),C(5,6,7)
void vGPIO_LCD_INT(void){
	vActive_CLK_GPIO(GPIO_CLK_B);
	vActive_CLK_GPIO(GPIO_CLK_C);
	
	vGPIO_UNLOCK(GPIO_B);
	vGPIO_UNLOCK(GPIO_C);
	vGPIO_Commit_Change_ALL(GPIO_B);
	vGPIO_Commit_Change_ALL(GPIO_C);
	
	vGPIO_MODE_SETTING_PIN(GPIO_B,Digital,Normal_GPIO,0);
	vGPIO_MODE_SETTING_PIN(GPIO_B,Digital,Normal_GPIO,1);
	vGPIO_MODE_SETTING_PIN(GPIO_B,Digital,Normal_GPIO,2);
	vGPIO_MODE_SETTING_PIN(GPIO_B,Digital,Normal_GPIO,3);
	vGPIO_MODE_SETTING_PIN(GPIO_B,Digital,Normal_GPIO,4);
	vGPIO_MODE_SETTING_PIN(GPIO_B,Digital,Normal_GPIO,5);
	vGPIO_MODE_SETTING_PIN(GPIO_B,Digital,Normal_GPIO,6);
	vGPIO_MODE_SETTING_PIN(GPIO_B,Digital,Normal_GPIO,7);
	
	vGPIO_MODE_SETTING_PIN(GPIO_C,Digital,Normal_GPIO,5);
	vGPIO_MODE_SETTING_PIN(GPIO_C,Digital,Normal_GPIO,6);
	vGPIO_MODE_SETTING_PIN(GPIO_C,Digital,Normal_GPIO,7);
	
	vGPIO_DIR_WRITE_ALL(GPIO_B,0xFF);
	
	vGPIO_DIR_WRITE_PIN(GPIO_C,5,OUTPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_C,6,OUTPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_C,7,OUTPUT);
	
	vGPIO_DATA_WRITE_ALL(GPIO_B,0x00);
	vGPIO_DATA_WRITE_ALL(GPIO_C,0x00);
}


//////////////////KEYPAD-----> GPIO A(4-->7),GPIO D(2,3,6,7)

void vGPIO_KeyPad_INT(void){
	vActive_CLK_GPIO(GPIO_CLK_A);
	vActive_CLK_GPIO(GPIO_CLK_D);
	
	vGPIO_UNLOCK(GPIO_A);
	vGPIO_UNLOCK(GPIO_D);
	
	vGPIO_Commit_Change_ALL(GPIO_A);
	vGPIO_Commit_Change_ALL(GPIO_D);
	
	vGPIO_MODE_SETTING_PIN(GPIO_A,Digital,Normal_GPIO,4);
	vGPIO_MODE_SETTING_PIN(GPIO_A,Digital,Normal_GPIO,5);
	vGPIO_MODE_SETTING_PIN(GPIO_A,Digital,Normal_GPIO,6);
	vGPIO_MODE_SETTING_PIN(GPIO_A,Digital,Normal_GPIO,7);
	
	vGPIO_MODE_SETTING_PIN(GPIO_D,Digital,Normal_GPIO,2);
	vGPIO_MODE_SETTING_PIN(GPIO_D,Digital,Normal_GPIO,3);
	vGPIO_MODE_SETTING_PIN(GPIO_D,Digital,Normal_GPIO,6);
	vGPIO_MODE_SETTING_PIN(GPIO_D,Digital,Normal_GPIO,7);
	
	vGPIO_DIR_WRITE_PIN(GPIO_D,2,INPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_D,3,INPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_D,6,INPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_D,7,INPUT);
	
	vGPIO_DIR_WRITE_PIN(GPIO_A,4,OUTPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_A,5,OUTPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_A,6,OUTPUT);
	vGPIO_DIR_WRITE_PIN(GPIO_A,7,OUTPUT);
	
	vGPIO_INPUT_MODE_PIN(GPIO_D,PULL_DOWN_R,2);
	vGPIO_INPUT_MODE_PIN(GPIO_D,PULL_DOWN_R,3);
	vGPIO_INPUT_MODE_PIN(GPIO_D,PULL_DOWN_R,6);
	vGPIO_INPUT_MODE_PIN(GPIO_D,PULL_DOWN_R,7);
	
	vGPIO_DATA_WRITE_SET_ALL(GPIO_A,0xF0);
}
